#image: "ghcr.io/jnull/{arch}-telegraf"
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:stable"
  armhf: "ghcr.io/hassio-addons/debian-base/armhf:stable"
  armv7: "ghcr.io/hassio-addons/debian-base/armv7:stable"
  i386: "ghcr.io/hassio-addons/debian-base/i386:stable"
args:
  TELEGRAF_VERSION: 1.30.2-1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Telegraf add-on"
  org.opencontainers.image.description: "Telegraf open source data collector"
  org.opencontainers.image.source: "https://github.com/jnull/hassio-addons"
  org.opencontainers.image.licenses: "MIT License"
