image: "ghcr.io/jnull/{arch}-telegraf"
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:7.8.1"
  amd64: "ghcr.io/home-assistant/amd64-base:7.8.1"
  armhf: "ghcr.io/home-assistant/armhf-base:7.8.1"
  armv7: "ghcr.io/home-assistant/armv7-base:7.8.1"
  i386: "ghcr.io/home-assistant/i386-base:7.8.1"
args:
  TELEGRAF_VERSION: 1.30.2-1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Telegraf add-on"
  org.opencontainers.image.description: "Telegraf open source data collector"
  org.opencontainers.image.source: "https://github.com/jnull/hassio-addons/tree/main/telegraf"
  org.opencontainers.image.licenses: "MIT License"
