name: Telegraf add-on
version: "1.34.3"
slug: hassio_telegraf
description: Telegraf open source data collector
url: "https://github.com/jnull/hassio-addons/tree/main/telegraf"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/jnull/{arch}-telegraf
init: false
startup: services
boot: manual
hassio_api: true
#hassio_role: default
auth_api: true
docker_api: true
host_network: true
#apparmor: true
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
privileged:
  - SYS_ADMIN
full_access: true
options:
  hostname: 94ee2189_hassio_telegraf
  interval: "10s"
  round_interval: true
  skip_processor_after_aggregation: true
  metric_batch_size: 1000
  metric_buffer_limit: 10000
  collection_jitter: "0s"
  flush_interval: "10s"
  flush_jitter: "0s"
  precision: "1ms"
  debug: false
  influxDB:
    enabled: true
    url: http://a0d7b954-influxdb:8086
    username: telegraf
    password: password
    db: telegraf
    retention_policy: autogen
  influxDBv2:
    enabled: false
    url: http://127.0.0.1:9999
    organization: ""
    token: ""
    bucket: ""
schema:
  hostname: str
  interval: str
  round_interval: bool
  skip_processor_after_aggregation: bool
  metric_batch_size: int
  metric_buffer_limit: int
  collection_jitter: str
  flush_interval: str
  flush_jitter: str
  precision: str?
  debug: bool
  influxDB:
    enabled: bool
    url: str
    db: str
    retention_policy: str?
    username: str?
    password: str?
  influxDBv2:
    enabled: bool
    url: str
    organization: str
    token: str
    bucket: str
