name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get current Version
        id: version
        run: |
          echo "version=$(echo ${{ vars.REF_TEST }} | sed "s/^.*\/v//g")" >> $GITHUB_OUTPUT
      - name: Print current Version
        env:
          TAG: ${{ steps.version.outputs.version }}
        run: |
          echo "Grabed Version is: $TAG"
      - name: shellcheck
        run: shellcheck telegraf/run.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker files
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --test \
            --all \
            --target telegraf \
            --docker-hub ghcr.io/${{ github.repository_owner }}
